version: '3.8'

services:
  db:
    image: docker.io/postgres:16.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: localpassword
      POSTGRES_DB: airflow_test
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - airflow_network
    restart: unless-stopped

  airflow-dags-deploy:
    build: .
    volumes:
      - airflow_dags:/opt/airflow/dags
      - airflow_plugins:/opt/airflow/plugins
    user: root
    entrypoint: ["sh"]
    command: >
      -c "
        echo 'Deploying DAGs to local development environment...' &&
        rm -rf /opt/airflow/dags/* &&
        cp -r /app/src/dags/* /opt/airflow/dags/ &&
        cp -r /app/src/utils /opt/airflow/dags/ &&
        cp -r /app/src/operators /opt/airflow/dags/ &&
        cp -r /app/src/hooks /opt/airflow/dags/ &&
        cp /app/requirements.txt /opt/airflow/dags/ &&
        chown -R 50000:0 /opt/airflow/dags &&
        echo 'DAGs and dependencies deployed successfully.'
      "

  airflow-standalone:
    image: apache/airflow:3.0.2
    volumes:
      - airflow_dags:/opt/airflow/dags
      - airflow_plugins:/opt/airflow/plugins
      - airflow_logs:/opt/airflow/logs
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:localpassword@db:5432/airflow_test
      AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/dags
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      AIRFLOW__CORE__FERNET_KEY: ''
      AIRFLOW__WEBSERVER__SECRET_KEY: 'a25c62d375079c43344b91f38ad6fce29d2a9a31456e15e5c5d8ec4f'
      PYTHONPATH: /opt/airflow/dags
      SHOPIFY_SHOP_NAME: ${SHOPIFY_SHOP_NAME:-test-shop}
      SHOPIFY_ACCESS_TOKEN: ${SHOPIFY_ACCESS_TOKEN:-test-token}
      DEVELOPMENT: "true"
      # Ensure DAG dependencies are available
      PIP_DISABLE_PIP_VERSION_CHECK: "1"
      PIP_NO_CACHE_DIR: "1"
      # Set admin password
      _AIRFLOW_WWW_USER_USERNAME: 'admin'
      _AIRFLOW_WWW_USER_PASSWORD: 'admin'
    depends_on:
      - db
      - airflow-dags-deploy
    networks:
      - airflow_network
    ports:
      - "8080:8080"
    command: |
      bash -c "
        echo 'Installing DAG dependencies...'
        if [ -f /opt/airflow/dags/requirements.txt ]; then
          pip install --no-cache-dir -r /opt/airflow/dags/requirements.txt
        else
          echo 'Requirements file not found, skipping dependency installation'
        fi
        echo 'Starting Airflow standalone...'
        airflow standalone
      "

  airflow-dags:
    build: .
    working_dir: /app
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
      - ./entrypoints:/app/entrypoints
    environment:
      PYTHONPATH: /app/src
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: localpassword
      POSTGRES_DB: airflow_test
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      SHOPIFY_SHOP_NAME: ${SHOPIFY_SHOP_NAME:-test-shop}
      SHOPIFY_ACCESS_TOKEN: ${SHOPIFY_ACCESS_TOKEN:-test-token}
      DEVELOPMENT: "true"
    depends_on:
      - db
    networks:
      - airflow_network
    entrypoint: ["./entrypoints/entrypoint.sh", "--interactive"]

  airflow-dags-test:
    build: .
    working_dir: /app
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
      - ./entrypoints:/app/entrypoints
    environment:
      PYTHONPATH: /app/src
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: localpassword
      POSTGRES_DB: airflow_test
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      SHOPIFY_SHOP_NAME: ${SHOPIFY_SHOP_NAME:-test-shop}
      SHOPIFY_ACCESS_TOKEN: ${SHOPIFY_ACCESS_TOKEN:-test-token}
      DEVELOPMENT: "true"
    depends_on:
      - db
    networks:
      - airflow_network
    entrypoint: ["./entrypoints/entrypoint_test.sh"]

  airflow-dags-e2e:
    build: .
    working_dir: /app
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
      - ./entrypoints:/app/entrypoints
    environment:
      PYTHONPATH: /app/src
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: localpassword
      POSTGRES_DB: airflow_test
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      SHOPIFY_SHOP_NAME: ${SHOPIFY_SHOP_NAME:-test-shop}
      SHOPIFY_ACCESS_TOKEN: ${SHOPIFY_ACCESS_TOKEN:-test-token}
      DEVELOPMENT: "true"
    depends_on:
      - db
    networks:
      - airflow_network
    entrypoint: ["./entrypoints/entrypoint_e2e.sh"]

volumes:
  postgres_data:
  airflow_dags:
  airflow_plugins:
  airflow_logs:

networks:
  airflow_network:
    driver: bridge