version: '3.8'

services:
  nginx_proxy:
    depends_on:
      - app_pxy6_com_shopify_deploy
    image: docker.io/jwilder/nginx-proxy
    container_name: nginx_proxy
    volumes:
      - /run/user/${RUNTIME_UID}/podman/podman.sock:/tmp/docker.sock:ro
    networks:
      - proxy_network
    ports:
      - "${HOST}:80:80"
      - "${HOST}:443:443"
    restart: unless-stopped

networks:
  proxy_network:
    driver: bridge
