version: '3.8'

services:
  nginx_proxy:
    image: docker.io/jwilder/nginx-proxy
    container_name: nginx_proxy
    volumes:
      - /run/user/${UID}/podman/podman.sock:/tmp/docker.sock:ro
    networks:
      - proxy_network
    restart: unless-stopped

networks:
  proxy_network:
    driver: bridge
