services:
  app_pxy6_com:
    image: "ghcr.io/xarionlabs/continuous_deployment_starter/app.pxy6.com:latest"
    depends_on:
      - db
      - pxy6_shopify_deploy
    environment:
      VIRTUAL_HOST: ${APP_PXY6_VIRTUAL_HOST}
      NODE_ENV: production
      SHOPIFY_APP_URL: https://${APP_PXY6_VIRTUAL_HOST}/
      SHOPIFY_CONFIG: ${SHOPIFY_CONFIG}
      AIRFLOW_API_URL: airflow:8080/api/v2
    labels:
      - "io.containers.autoupdate=registry"
    expose:
      - "3000"
    networks:
      - db_network
      - proxy_network
      - airflow_network
    restart: unless-stopped
    secrets:
      - PSQL_PXY6_PASSWORD
      - SHOPIFY_API_KEY
      - SHOPIFY_API_SECRET
      - SHOPIFY_CLI_PARTNERS_TOKEN

  pxy6_shopify_deploy:
    image: "ghcr.io/xarionlabs/continuous_deployment_starter/app.pxy6.com:latest"
    environment:
      SHOPIFY_CONFIG: ${SHOPIFY_CONFIG}
    labels:
      - "io.containers.autoupdate=registry"
    entrypoint: ["./entrypoints/entrypoint_shopify_config.sh"]
    restart: "no"
    secrets:
      - SHOPIFY_CLI_PARTNERS_TOKEN
      - SHOPIFY_API_KEY

networks:
  db_network:
    driver: bridge
  proxy_network:
    driver: bridge
  airflow_network:
    driver: bridge
