services:
  app_pxy6_com:
    image: "ghcr.io/xarionlabs/continuous_deployment_starter/app.pxy6.com:${APP_VERSION}"
    depends_on:
      - db
      - app_pxy6_com_shopify_deploy
    environment:
      VIRTUAL_HOST: ${APP_PXY6_VIRTUAL_HOST}
      NODE_ENV: production
      SHOPIFY_APP_URL: ${APP_PXY6_VIRTUAL_HOST}
      SHOPIFY_CONFIG: ${SHOPIFY_CONFIG}
    expose:
      - "3000"
    networks:
      - db_network
      - proxy_network
    restart: unless-stopped
    secrets:
      - PSQL_APP_PXY6_PASSWORD
      - SHOPIFY_API_KEY
      - SHOPIFY_API_SECRET
      - SHOPIFY_CLI_PARTNERS_TOKEN


  app_pxy6_com_shopify_deploy:
    image: "ghcr.io/xarionlabs/continuous_deployment_starter/app.pxy6.com:${APP_VERSION}"
    environment:
      SHOPIFY_CONFIG: ${SHOPIFY_CONFIG}
    entrypoint: ["./entrypoints/entrypoint_shopify_config.sh"]
    restart: "no"
    secrets:
      - SHOPIFY_CLI_PARTNERS_TOKEN
      - SHOPIFY_API_KEY

networks:
  db_network:
    driver: bridge
  proxy_network:
    driver: bridge
