services:
  pxy6_app:
    image: "ghcr.io/xarionlabs/continuous_deployment_starter/app.pxy6.com:latest"
    depends_on:
      - db
      - migrate_db_pxy6
      - shopify_deploy_pxy6
    environment:
      VIRTUAL_HOST: ${APP_PXY6_VIRTUAL_HOST}
      NODE_ENV: production
      SHOPIFY_APP_URL: https://${APP_PXY6_VIRTUAL_HOST}/
      SHOPIFY_CONFIG: ${SHOPIFY_CONFIG}
    labels:
      - "io.containers.autoupdate=registry"
    expose:
      - "3000"
    networks:
      - db_network
      - proxy_network
    restart: unless-stopped
    secrets:
      - PSQL_PXY6_PASSWORD
      - SHOPIFY_API_KEY
      - SHOPIFY_API_SECRET
      - SHOPIFY_CLI_PARTNERS_TOKEN


  pxy6_migrate_db:
    image: "ghcr.io/xarionlabs/continuous_deployment_starter/app.pxy6.com:latest"
    environment:
      NODE_ENV: production
    depends_on:
      - db
    labels:
      - "io.containers.autoupdate=registry"
    entrypoint: ["./entrypoints/entrypoint_migrate_db.sh"]
    restart: "no"
    secrets:
      - SHOPIFY_CLI_PARTNERS_TOKEN
      - SHOPIFY_API_KEY

  pxy6_shopify_deploy:
    image: "ghcr.io/xarionlabs/continuous_deployment_starter/app.pxy6.com:latest"
    environment:
      SHOPIFY_CONFIG: ${SHOPIFY_CONFIG}
    labels:
      - "io.containers.autoupdate=registry"
    entrypoint: ["./entrypoints/entrypoint_shopify_config.sh"]
    restart: "no"
    secrets:
      - SHOPIFY_CLI_PARTNERS_TOKEN
      - SHOPIFY_API_KEY

networks:
  db_network:
    driver: bridge
  proxy_network:
    driver: bridge
