version: '3.8'

services:
  db:
    image: docker.io/postgres:16.6
    container_name: db
    environment:
      POSTGRES_USER: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - db_network
    restart: unless-stopped
    secrets:
      - POSTGRES_PASSWORD

  user_management:
    image: ghcr.io/xarionlabs/continuous_deployment_starter/utilities-user_management:latest
    volumes:
      - ./users.csv:/app/users.csv
    environment:
      POSTGRES_USER: postgres
    labels:
      - "io.containers.autoupdate=registry"
    depends_on:
      - db
    networks:
      - db_network
    restart: "no"
    secrets:
      - POSTGRES_PASSWORD
      - PSQL_APP_1_MIGRATIONS_PASSWORD
      - PSQL_APP_1_PASSWORD
      - PSQL_PXY6_PASSWORD

volumes:
  postgres_data:

networks:
  db_network:
    driver: bridge