version: '3.8'

services:
  db:
    image: docker.io/postgres:16.6
    environment:
      POSTGRES_USER: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - db_network
    restart: unless-stopped
    secrets:
      - POSTGRES_PASSWORD

volumes:
  postgres_data:

networks:
  db_network:
    driver: bridge