version: '3.8'

services:
  db:
    image: docker.io/postgres:16.6
    environment:
      POSTGRES_USER: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - db_network
    restart: unless-stopped
    secrets:
      - POSTGRES_PASSWORD

  user_management:
    build: utilities/user_management
    entrypoint: entrypoint.sh
    volumes:
      - services/01_postgres/users.csv:/app/users.csv
    environment:
      POSTGRES_USER: postgres
    depends_on:
      - db
    networks:
      - db_network
    restart: no
    secrets:
      - POSTGRES_PASSWORD
      - PSQL_APP_1_MIGRATIONS_PASSWORD
      - PSQL_APP_1_PASSWORD

volumes:
  postgres_data:

networks:
  db_network:
    driver: bridge