version: '3.8'

# This override file provides a local development setup with SQLite
# Use: docker-compose -f docker-compose.yaml -f docker-compose.override.yml up
# or simply: docker-compose up (docker-compose automatically uses override files)

services:
  app:
    environment:
      DATABASE_PROVIDER: sqlite
      DATABASE_URL: file:./dev.db
    depends_on: []  # Remove dependency on PostgreSQL db service
    
  tests:
    environment:
      DATABASE_PROVIDER: sqlite
      DATABASE_URL: file:./test.db
    depends_on: []  # Remove dependency on PostgreSQL db service
    
  e2e_tests:
    environment:
      DATABASE_PROVIDER: sqlite
      DATABASE_URL: file:./e2e.db
    depends_on: []  # Remove dependency on PostgreSQL db service

# Note: PostgreSQL service is still available but not used in local development