# Production docker-compose file for PostgreSQL setup
# Use: docker-compose -f docker-compose.yaml -f docker-compose.prod.yml up

services:
  app:
    environment:
      DATABASE_PROVIDER: postgresql
      DATABASE_URL: postgresql://pxy6:${PSQL_PXY6_PASSWORD}@db:5432/pxy6
    depends_on:
      - db
    
  tests:
    environment:
      DATABASE_PROVIDER: postgresql
      DATABASE_URL: postgresql://pxy6:${PSQL_PXY6_PASSWORD}@db:5432/pxy6
    depends_on:
      - db
    
  e2e_tests:
    environment:
      DATABASE_PROVIDER: postgresql
      DATABASE_URL: postgresql://pxy6:${PSQL_PXY6_PASSWORD}@db:5432/pxy6
    depends_on:
      - db