version: '3.8'

services:
  db:
    image: docker.io/postgres:16.6
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASS}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - db_network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  db_network:
    driver: bridge