
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qgywfvfevmquvsclodyu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFneXdmdmZldm1xdXZzY2xvZHl1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxNDA3NzMsImV4cCI6MjA2MjcxNjc3M30.LrGopOxOXy5605O9Pz7n5IaobaakKdHQ7pAAjM1o4iQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
