# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "0d2687ceba3f91bcdd7c7a03b212175f"
name = "pxy6-staging-changes-test"
handle = "pxy6-staging-changes-test"
application_url = "https://staging.pxy6.com/"
embedded = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update", "app/uninstalled" ]
  uri = "/webhooks"
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]

[access_scopes]
scopes = "read_all_orders,read_customers,read_inventory,read_metaobjects,read_orders,read_product_listings,read_products,read_returns,write_metaobjects"

[auth]
redirect_urls = ["https://staging.pxy6.com/auth/callback", "https://staging.pxy6.com/auth/shopify/callback", "https://staging.pxy6.com/api/auth/callback"]

[pos]
embedded = false

[build]
include_config_on_deploy = true
