services:
  app_1:
    image: "ghcr.io/xarionlabs/continuous_deployment_starter/app_1:${APP_VERSION}"
    depends_on:
      - db
    environment:
      VIRTUAL_HOST: ${APP_1_VIRTUAL_HOST}
      DATABASE_URL: postgresql://myuser:mypassword@db:5432/mydatabase
    expose:
      - "8080"
    networks:
      - db_network
      - proxy_network
    restart: unless-stopped
    secrets:
      - POSTGRES_PASSWORD
      - STREAMLIT_OAUTH_CLIENT_ID
      - STREAMLIT_OAUTH_CLIENT_SECRET
      - STREAMLIT_OAUTH_COOKIE_SECRET

networks:
  db_network:
    driver: bridge
  proxy_network:
    driver: bridge

