name: e2e-tests

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

permissions:
  contents: read
  packages: read

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    environment: ${{ inputs.environment }}
    
    steps:
      - uses: actions/checkout@v4
        with:
          ref: releases
      
      - name: Load version from services/version.env
        id: load_version
        run: |
          if [ -f services/version.env ]; then
            source services/version.env
            echo "version=${APP_VERSION}" >> $GITHUB_OUTPUT
          else
            echo "Error: services/version.env not found"
            exit 1
          fi

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Find applications with e2e tests
        id: find_applications
        run: |
          # Find applications that have both Dockerfile and e2e entrypoint
          VALID_E2E_APPS=""
          for app_dir in applications/*/; do
            app_name=$(basename "$app_dir")
            if [ -f "$app_dir/Dockerfile" ] && [ -f "$app_dir/entrypoints/entrypoint_e2e.sh" ]; then
              VALID_E2E_APPS="$VALID_E2E_APPS$app_name"$'\n'
            fi
          done
          
          # Remove trailing newline and convert to JSON
          VALID_E2E_APPS=$(echo "$VALID_E2E_APPS" | sed '/^$/d')
          echo "applications=$(echo "$VALID_E2E_APPS" | jq -R -s -c 'split("\n") | map(select(length > 0))')" >> $GITHUB_OUTPUT

      - name: Run e2e tests for each application
        env:
          VARS_JSON: ${{ toJson(vars) }}
          REGISTRY: ghcr.io
          TAG: ${{ steps.load_version.outputs.version }}
          ENVIRONMENT: ${{ inputs.environment }}
        run: |
          set -e
          
          # Function for structured logging
          log_with_timestamp() {
            echo "[$(date '+%Y-%m-%d %H:%M:%S')] $1"
          }
          
          log_with_timestamp "Starting E2E tests for $ENVIRONMENT environment"
          
          # Create a temporary .env file with all environment variables
          echo "APP_ENV=$ENVIRONMENT" > .env
          echo "APP_VERSION=$TAG" >> .env
          python3 -c "import os, json; data = json.loads(os.environ['VARS_JSON']); [print(f'{k}={json.dumps(v)[1:-1]}') for k, v in data.items()]" >> .env 2>/dev/null || true
          
          log_with_timestamp "Environment variables loaded into .env file"
          
          # Get applications array
          APPS=$(echo '${{ steps.find_applications.outputs.applications }}' | jq -r '.[]')
          
          if [ -z "$APPS" ]; then
            echo "::notice::No applications found with e2e tests"
            exit 0
          fi
          
          # Run tests for each application
          failed_apps=()
          for app in $APPS; do
            echo "::group::Running e2e tests for $app"
            log_with_timestamp "Running e2e tests for $app in $ENVIRONMENT environment"
            
            # Debug information (without sensitive data)
            log_with_timestamp "Image: $REGISTRY/${{ github.repository }}/$app:$TAG"
            
            # Run the e2e tests using the application's own entrypoint with timeout
            if timeout 600 docker run --rm \
              --network host \
              --env-file .env \
              --entrypoint /app/entrypoints/entrypoint_e2e.sh \
              "$REGISTRY/${{ github.repository }}/$app:$TAG" 2>/dev/null; then
              log_with_timestamp "E2E tests passed for $app"
            else
              log_with_timestamp "E2E tests failed for $app in $ENVIRONMENT environment"
              # Show test output only on failure
              echo "::group::Test output for debugging"
              docker run --rm \
                --network host \
                --env-file .env \
                --entrypoint /app/entrypoints/entrypoint_e2e.sh \
                "$REGISTRY/${{ github.repository }}/$app:$TAG" || true
              echo "::endgroup::"
              failed_apps+=("$app")
            fi
            
            echo "::endgroup::"
          done
          
          # Clean up environment file
          rm -f .env 2>/dev/null || true
          
          # Report results
          if [ ${#failed_apps[@]} -gt 0 ]; then
            log_with_timestamp "E2E tests failed for the following applications: ${failed_apps[*]}"
            exit 1
          else
            log_with_timestamp "All E2E tests passed successfully"
          fi
        timeout-minutes: 20 