name: live-release
on:
  workflow_run:
    workflows: ["staging-release"]
    branches: [main]
    types: 
      - completed

jobs:
  release:
    runs-on: ubuntu-latest
    environment: live
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v1.2.0
        env:
          VARS_JSON: ${{ toJson(vars) }}
          SECRETS_JSON: ${{ toJson(secrets) }}
        with:
          host: ${{ vars.HOST }}
          username: ${{ vars.USERNAME }}
          key: ${{ secrets.KEY }}
          envs: VARS_JSON, SECRETS_JSON
          script: |
            set -e
            cd ~/runtime/continuous_deployment_starter
            export PATH=$PATH:$(pwd)/.github/workflows/scripts/
            git checkout releases
            git pull origin releases
            refresh_podman_secrets.sh "$SECRETS_JSON"
            create_env_variables.sh
            set -o allexport
            source services/version.env
            source .env
            set +o allexport
            check-service-envs.sh
            generate_quadlets.sh
            start_all_services.sh