name: live-release
on:
  workflow_run:
    workflows: ["staging-release"]
    branches: [main]
    types: 
      - completed

permissions: read-all

jobs:
  release:
    runs-on: ubuntu-latest
    environment: live
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v1.2.0
        env:
          VARS_JSON: ${{ toJson(vars) }}
        with:
          host: ${{ vars.HOST }}
          username: ${{ vars.USERNAME }}
          key: ${{ secrets.KEY }}
          envs: VARS_JSON
          script: |
            set -e
            podman login gchr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
            cd ~/runtime/continuous_deployment_starter
            export PATH=$PATH:$(pwd)/.github/workflows/scripts/
            git checkout releases
            git pull origin releases
            refresh_podman_secrets.sh "${{ github.repository }}" "${{ secrets.GITHUB_TOKEN }}" live
            create_and_source_env_variables.sh
            check-service-envs.sh
            generate_quadlets.sh
            start_all_services.sh