name: staging-release

on:
  workflow_call:
    inputs:
      build_tag:
        description: 'Build tag to use'
        required: true
        type: string

jobs:
  release:
    uses: ./.github/workflows/release.yml
    timeout-minutes: 30
    with:
      environment: staging
      build_tag: ${{ github.event.inputs.build_tag }}
    secrets:
      KEY: ${{ secrets.KEY }}